# Generated by Django 4.1.7 on 2023-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_rename_timeline_board_input_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='input_type',
            field=models.TextField(choices=[('input_text', '텍스트 요약'), ('input_youtube', 'Youtube 영상 링크 입력'), ('input_video', '영상 파일 업로드')], null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
