# Generated by Django 4.1.7 on 2023-03-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='timeline',
            new_name='input_text',
        ),
        migrations.RemoveField(
            model_name='board',
            name='original',
        ),
        migrations.RemoveField(
            model_name='board',
            name='summary',
        ),
        migrations.AddField(
            model_name='board',
            name='result_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='summary_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='timeline_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='board',
            name='youtube_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
