# Generated by Django 4.1.7 on 2023-04-05 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('input_type', models.TextField(choices=[('input_text', '텍스트 요약'), ('input_youtube', 'Youtube 영상 링크 입력'), ('input_video', '영상 파일 업로드')], null=True)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('input_youtube', models.TextField(blank=True, null=True)),
                ('input_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('total_text', models.TextField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('timeline_text', models.TextField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', markdownx.models.MarkdownxField()),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
