# Generated by Django 4.1.7 on 2023-03-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_board_result_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='video_file',
            new_name='input_video',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='youtube_link',
            new_name='input_youtube',
        ),
    ]
