# Generated by Django 4.1.7 on 2023-03-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_rename_video_file_board_input_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='total_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
